/**
 * Endpoint registry — the single source of truth for every API path this
 * dashboard uses.
 *
 * No component and no lib module builds a URL by hand. Each entry is a
 * function of its parameters, so a route change in gcr-api-clean is a one-line
 * edit here rather than a search across the whole app.
 *
 * Same idea as Admin-dashboard-main/src/api/endpoints.js. Paths are relative
 * to GCR_API_BASE and mirror the routers mounted in gcr-api-clean/server.js:
 *
 *   /api/business       → routes/business-data.js   (this business's own data)
 *   /api/business-auth  → routes/business-auth.js   (phone sign-up and sign-in)
 *   /api/auth           → routes/auth.js            (invite links)
 *   /api/gcr            → routes/gcr.js             (public listings, claims)
 */

const BUSINESS = '/api/business'
const BUSINESS_AUTH = '/api/business-auth'
const AUTH = '/api/auth'
const GCR = '/api/gcr'
const BOOKING = '/api/booking'

/** Encode a path segment so slugs and ids with odd characters stay valid. */
const seg = (value) => encodeURIComponent(String(value ?? ''))

export const endpoints = {
  // ------------------------------------------------------------- session ---
  auth: {
    /** Who this session is, what it owns, and whether it is an admin. */
    me: () => `${BUSINESS}/me`,

    // Phone sign-up: number → code → business name → account.
    signupCode: () => `${BUSINESS_AUTH}/phone`,
    verifySignupCode: () => `${BUSINESS_AUTH}/verify`,
    similar: () => `${BUSINESS_AUTH}/similar`,
    register: () => `${BUSINESS_AUTH}/register`,

    // Phone sign-in: same two steps, no password at either end.
    signinCode: () => `${BUSINESS_AUTH}/signin`,
    verifySigninCode: () => `${BUSINESS_AUTH}/signin-verify`,

    /** For the invite accounts that really do have a password. */
    password: () => `${BUSINESS_AUTH}/password`,
    refresh: () => `${BUSINESS_AUTH}/refresh`,
    signout: () => `${BUSINESS_AUTH}/signout`,

    // Invite links generated by an admin and texted to a business.
    invite: (token) => `${AUTH}/invite/${seg(token)}`,
    acceptInvite: () => `${AUTH}/accept-invite`,
  },

  // ------------------------------------------------- this business's data ---
  business: {
    /** The slug tables and their editable columns, computed server-side. */
    schema: () => `${BUSINESS}/schema`,
    /** Every section with rows, in one call. Replaces 316 browser requests. */
    sections: () => `${BUSINESS}/sections`,
    /** One section, paged — for refreshing after an edit. */
    table: (table) => `${BUSINESS}/${seg(table)}`,
    /** Create, update, delete. The slug is never in the path or the body. */
    create: (table) => `${BUSINESS}/${seg(table)}`,
    update: (table, id) => `${BUSINESS}/${seg(table)}/${seg(id)}`,
    remove: (table, id) => `${BUSINESS}/${seg(table)}/${seg(id)}`,
    /** Distinct entity_type values, read live rather than hardcoded. */
    industries: () => `${BUSINESS}/industries`,
  },

  // ------------------------------------------------------- the App Store ---
  // Scoped to one business. The API resolves which one from the session via
  // entity_owners, so no path here carries a slug either.
  connections: {
    list: () => '/api/connections',
    connect: (toolId) => `/api/connections/${seg(toolId)}/connect`,
    refresh: (toolId) => `/api/connections/${seg(toolId)}/refresh`,
    disconnect: (toolId) => `/api/connections/${seg(toolId)}`,
  },

  // ---------------------------------------------------- booking platform ---
  // The modular booking engine in gcr-api-clean (routes/booking.js).
  //
  // Same rule as everything above: no owner path carries a slug. The API
  // resolves which business is calling from the session through
  // entity_owners, so there is nothing this dashboard could put in a
  // request that would let it configure, read or refund for another one.
  //
  // The only slug that appears here is in `publicPage`, which is the
  // customer-facing preview of a page this business publishes — the same
  // URL a stranger would open.
  booking: {
    /** The vertical catalogue: charter, parasail, jet ski, tour, … */
    templates: () => `${BOOKING}/templates`,
    /** Is this business ready to take bookings, and how is it doing? */
    summary: () => `${BOOKING}/summary`,

    products: () => `${BOOKING}/products`,
    product: (id) => `${BOOKING}/products/${seg(id)}`,

    // Rates, schedules, extras and resources are the same four verbs each.
    collection: (name) => `${BOOKING}/${seg(name)}`,
    collectionItem: (name, id) => `${BOOKING}/${seg(name)}/${seg(id)}`,

    orders: () => `${BOOKING}/orders`,
    order: (id) => `${BOOKING}/orders/${seg(id)}`,
    refund: (id) => `${BOOKING}/orders/${seg(id)}/refund`,
    calendar: () => `${BOOKING}/calendar`,

    // Stripe Connect. The dashboard never sees a key or an account token —
    // it asks for a one-time link and sends the owner to Stripe.
    paymentAccount: () => `${BOOKING}/payments/account`,
    onboard: () => `${BOOKING}/payments/account/onboard`,
    refreshAccount: () => `${BOOKING}/payments/account/refresh`,
    stripeLogin: () => `${BOOKING}/payments/account/login-link`,

    settings: () => `${BOOKING}/settings`,

    /** The public booking page, as a customer sees it. */
    publicPage: (slug) => `${BOOKING}/public/${seg(slug)}`,
  },

  // ------------------------------------------------------ public listings ---
  gcr: {
    entity: (slug) => `${GCR}/entity/${seg(slug)}`,
    entities: () => `${GCR}/entities`,
    claim: () => `${GCR}/claim`,
  },
}

export default endpoints
