/**
 * Endpoint registry — the single source of truth for every API path this
 * dashboard uses.
 *
 * No component and no lib module builds a URL by hand. Each entry is a
 * function of its parameters, so a route change in gcr-api-clean is a one-line
 * edit here rather than a search across the whole app.
 *
 * Same idea as Admin-dashboard-main/src/api/endpoints.js. Paths are relative
 * to GCR_API_BASE and mirror the routers mounted in gcr-api-clean/server.js:
 *
 *   /api/business       → routes/business-data.js   (this business's own data)
 *   /api/business/automations → routes/automations.js (what was pushed to it)
 *   /api/business-auth  → routes/business-auth.js   (phone sign-up and sign-in)
 *   /api/auth           → routes/auth.js            (invite links)
 *   /api/gcr            → routes/gcr.js             (public listings, claims)
 */

const BUSINESS = '/api/business'
const BUSINESS_AUTH = '/api/business-auth'
const AUTH = '/api/auth'
const GCR = '/api/gcr'

/** Encode a path segment so slugs and ids with odd characters stay valid. */
const seg = (value) => encodeURIComponent(String(value ?? ''))

export const endpoints = {
  // ------------------------------------------------------------- session ---
  auth: {
    /** Who this session is, what it owns, and whether it is an admin. */
    me: () => `${BUSINESS}/me`,

    // Phone sign-up: number → code → business name → account.
    signupCode: () => `${BUSINESS_AUTH}/phone`,
    verifySignupCode: () => `${BUSINESS_AUTH}/verify`,
    similar: () => `${BUSINESS_AUTH}/similar`,
    register: () => `${BUSINESS_AUTH}/register`,

    // Phone sign-in: same two steps, no password at either end.
    signinCode: () => `${BUSINESS_AUTH}/signin`,
    verifySigninCode: () => `${BUSINESS_AUTH}/signin-verify`,

    /** For the invite accounts that really do have a password. */
    password: () => `${BUSINESS_AUTH}/password`,
    refresh: () => `${BUSINESS_AUTH}/refresh`,
    signout: () => `${BUSINESS_AUTH}/signout`,

    // Invite links generated by an admin and texted to a business.
    invite: (token) => `${AUTH}/invite/${seg(token)}`,
    acceptInvite: () => `${AUTH}/accept-invite`,
  },

  // ------------------------------------------------- this business's data ---
  business: {
    /** The slug tables and their editable columns, computed server-side. */
    schema: () => `${BUSINESS}/schema`,
    /** Every section with rows, in one call. Replaces 316 browser requests. */
    sections: () => `${BUSINESS}/sections`,
    /** One section, paged — for refreshing after an edit. */
    table: (table) => `${BUSINESS}/${seg(table)}`,
    /** Create, update, delete. The slug is never in the path or the body. */
    create: (table) => `${BUSINESS}/${seg(table)}`,
    update: (table, id) => `${BUSINESS}/${seg(table)}/${seg(id)}`,
    remove: (table, id) => `${BUSINESS}/${seg(table)}/${seg(id)}`,
    /** Distinct entity_type values, read live rather than hardcoded. */
    industries: () => `${BUSINESS}/industries`,
  },

  // ------------------------------------------------------- the App Store ---
  // Scoped to one business. The API resolves which one from the session via
  // entity_owners, so no path here carries a slug either.
  // -------------------------------------------------------------- store ---
  // What the operator made available to this business, and what it has.
  // Scoped by the session; no slug is ever sent.
  store: {
    list: () => '/api/store',
    install: (id) => `/api/store/${seg(id)}/install`,
    update: (id) => `/api/store/${seg(id)}/update`,
    status: (id, verb) => `/api/store/${seg(id)}/${seg(verb)}`,
    config: (id) => `/api/store/${seg(id)}/config`,
    item: (id) => `/api/store/${seg(id)}`,
  },

  connections: {
    list: () => '/api/connections',
    connect: (toolId) => `/api/connections/${seg(toolId)}/connect`,
    refresh: (toolId) => `/api/connections/${seg(toolId)}/refresh`,
    disconnect: (toolId) => `/api/connections/${seg(toolId)}`,
  },

  // ----------------------------------------------------- the Ghost box(es) ---
  // Scoped to one business by the session. The box is reached through the
  // relay: a request is queued here, the box pulls it, the answer comes back.
  nodes: {
    list: () => '/api/nodes',
    enrol: () => '/api/nodes',
    revoke: (id) => `/api/nodes/${seg(id)}`,
    request: (id) => `/api/nodes/${seg(id)}/requests`,
    mcpTokens: (id) => `/api/nodes/${seg(id)}/mcp-tokens`,
    createMcpToken: (id) => `/api/nodes/${seg(id)}/mcp-token`,
    revokeMcpToken: (id, tokenId) => `/api/nodes/${seg(id)}/mcp-token/${seg(tokenId)}`,
    requestStatus: (id, rid) => `/api/nodes/${seg(id)}/requests/${seg(rid)}`,
  },

  // --------------------------------------------------------- automations ---
  // What the operator pushed to this business, at the version it was given.
  // Scoped by the session, like everything under /api/business.
  automations: {
    list: () => `${BUSINESS}/automations`,
    update: (id) => `${BUSINESS}/automations/${seg(id)}`,
    run: (id) => `${BUSINESS}/automations/${seg(id)}/run`,
    runs: (id) => `${BUSINESS}/automations/${seg(id)}/runs`,
    upgrade: (id) => `${BUSINESS}/automations/${seg(id)}/update`,
    rotateHook: (id) => `${BUSINESS}/automations/${seg(id)}/hook/rotate`,
  },

  // ------------------------------------------------------ public listings ---
  gcr: {
    entity: (slug) => `${GCR}/entity/${seg(slug)}`,
    entities: () => `${GCR}/entities`,
    claim: () => `${GCR}/claim`,
  },
}

export default endpoints
